app = "suiza-product-scanner"
primary_region = "gru"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "8080"
  DJANGO_ALLOWED_HOSTS = "*"

[deploy]
  release_command = "python manage.py migrate --noinput"

[[mounts]]
  source = "products_data"
  destination = "/data"
  processes = ["app"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[vm]
  memory = "1024"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.health]
    type = "http"
    port = 8080
    interval = "30s"
    timeout = "5s"
    path = "/api/health"
